name: Build Radicale Data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone vCards
        run: git clone https://github.com/metowolf/vCards.git

      - name: Install dependencies
        run: |
          cd vCards
          npm install

      - name: Build radicale data
        run: |
          cd vCards
          npm run-script radicale

      - name: Zip radicale data
        run: |
          zip -r radicale-data.zip vCards/radicale

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: radicale-${{ github.run_id }}
          files: radicale-data.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
